wip

diff --git a/.github/workflows/check-new-releases.yaml b/.github/workflows/check-new-releases.yaml
--- a/.github/workflows/check-new-releases.yaml
+++ b/.github/workflows/check-new-releases.yaml
@@ -145,7 +145,18 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           release_name: Release ${{ matrix.version }}
-          suppress_errors: true
+          tag_name: ${{ matrix.version }}
+          suppress_errors: false
+      
+      - name: Get tarball name
+        id: get-tarball-name
+        run: |
+          cd output/${{ matrix.version }}/
+          # extract jars from tarball
+          if [ ls ${{ inputs.tarball-name-regex }} | wc -l} != 1]; then
+            echo "Tarball file not found with regex: ${{ inputs.tarball-name-regex }}"
+            exit 1
+          tarball_filename=$(ls ${{ inputs.tarball-name-regex }})
 
       - name: Release the package
         id: create-new-release
@@ -162,7 +173,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create-new-release.outputs.upload_url }}
-          asset_path: ${{ env.OUTPUT_DIR }}/${{ matrix.version }}/${{ matrix.version }}-bin-custom-spark.tgz
+          asset_path: ${{ env.OUTPUT_DIR }}/${{ matrix.version }}/${{ step.get-tarball-name.tarball_filename }}
           asset_name: ${{ matrix.version }}.tgz
           asset_content_type: application/zip
 
@@ -172,19 +183,14 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create-new-release.outputs.upload_url }}
-          asset_path: output/${{ matrix.version }}/${{ matrix.version }}-bin-custom-spark.tgz.sha512
+          asset_path: output/${{ matrix.version }}/${{ step.get-tarball-name.tarball_filename }}.tgz.sha512
           asset_name: ${{ matrix.version }}.sha512
           asset_content_type: application/txt
 
       - name: Upload Java dependencies
         run: |
-          cd output/${{ matrix.version }}/
-          # extract jars from tarball
           
-          if [ ls ${{ inputs.tarball-name-regex }} | wc -l} != 1]; then
-            echo "Tarball file not found with regex: ${{ inputs.tarball-name-regex }}"
-            exit 1
-          tarball_file = $(ls ${{ inputs.tarball-name-regex }}) 
+          tarball_file = ${{ step.get-tarball-name.tarball_filename }}
           mkdir tmp && tar xf $tarball_file -C tmp --strip-components 1
           cd tmp
           find . -type f -name "*.jar" | awk -F '/' '{print $NF}' > tarball_jars.txt
